### ISSUE TITLE
Any plan to support CentOS ?

### ISSUE THREAD

**Issue by pivdets** [avsm/setup-ocaml#42]
I'm trying to add [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) in a CentOS, according to the source code:

```
  await exec(
    "sudo apt-get -y install bubblewrap ocaml-native-compilers ocaml-compiler-libs musl-tools"
  );
```

It seems that we only support Ubuntu at this moment.

PS: I've tried to config the opam and ocaml in my CentOS and remove the following part:

```
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
```

Then I got another error:

```
 Run opam pin add hello.dev . --no-action0s
  shell: /usr/bin/bash -e {0}
Run opam pin add hello.dev . --no-action
  opam pin add hello.dev . --no-action
  shell: /usr/bin/bash -e {0}
Package hello does not exist, create as a NEW package? [Y/n] n
##[error]Process completed with exit code 10.
```

And now my wordflow.yml would be:

```yaml
name: Main workflow

on:  
  - push

jobs:
  build:
    strategy:
      fail-fast: false    

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: opam pin add hello.dev . --no-action

      - run: opam depext hello --yes --with-doc --with-test

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
```

**Comment by pivdets** [comment]
After install dependencies by 

> opam install async cohttp-async core ppx_let uri yojson

Now the following workflow work for me:

```yaml
name: Main workflow

on:  
  - push

jobs:
  build:
    strategy:
      fail-fast: false    

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - run: dune external-lib-deps --missing @@default
      
      - run: opam install . -y --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
```
